# Table of contents 
1. [Running Models](#running_model)
    1. [Real Data](#real_data)
        1. [Final Need Output](#final_need_output)
    2. [Dummy Data](#dummy_data)
        1. [Testing 8 Groups for Symmetric Improvements & Disimprovements](#10_groups_sym)
            1. [Group 1](#dummy_group_1)

In [1]:
%run decision_support_model.ipynb

In [2]:
#Some useful settings
#np.set_printoptions(threshold=sys.maxsize)
#%pprint
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_rows', 10)
#pd.set_option('display.max_columns', None)

## Running Model <a name="running_model"></a>

### Real Data <a name="real_data"></a>

data name: ibhs_all_imp and fbmhs_all_imp

In [3]:
old_ibhs_df = pd.read_csv('ibhs_all_improv_table.csv')
old_fbmh_df = pd.read_csv('fbmhs_all_improv_table.csv')
print("There are ", old_ibhs_df.shape[0], "IBHS Patients")
print("There are ", old_fbmh_df.shape[0], "FBMH Patients")
print('Total, we have', old_ibhs_df.shape[0]+old_fbmh_df.shape[0], 'patients')

There are  3819 IBHS Patients
There are  2075 FBMH Patients
Total, we have 5894 patients


In [4]:
all_column_names = ['pp01', 'pp02', 'pp03', 'pp04', 
                    'pp05', 'pp06', 'pp07', 'pp08', 
                    'pp09', 'pp10', 'pp11', 'pp12', 
                    'pp13', 'pp14', 'pp15', 'pp16', 
                    'pp17', 'pp18', 'pp19', 'rb01', 
                    'rb02', 'rb03', 'rb04', 'rb05', 
                    'rb06', 'rb07', 'rb08', 'rb09', 
                    'rb10', 'rb11', 'rb12', 'rb13', 
                    'rb14', 'rb15', 'rb16', 'rb17', 
                    'rb18', 'rb19', 'rb20', 'rb21', 
                    'rb22', 'rb23', 'rb24', 'rb25', 
                    'rb26', 'rb27', 'rb28', 'fu01', 
                    'fu02', 'fu03', 'fu04', 'fu05', 
                    'fu06', 'fu07', 'fu08', 'fu09', 
                    'fu10', 'fu11', 'fu12', 'fu13', 
                    'fu14', 'fu15', 'fu16', 'fu17', 
                    'fu18', 'fu19', 'fu20', 'fu21', 
                    'fu22', 'fu23', 'fu24', 'fu25', 
                    'fu26', 'fu27', 'cs01', 'cn01', 
                    'cn02', 'cn03', 'cn04', 'cn05', 
                    'cn06', 'cn07', 'st01', 'st02', 
                    'st03', 'st04', 'st05', 'st06', 
                    'st07', 'st08', 'st09', 'st10', 'st11', 'st12']

In [5]:
# keep only 53 top-level items
# change index into column names
old_ibhs_df.columns = all_column_names
old_fbmh_df.columns = all_column_names
# keep the needed columns 
column_names_df = pd.read_csv('CANS Items for MILP Profile - Sheet1.csv')
column_names = list(column_names_df['Standradized Field'])
ibhs_df = old_ibhs_df[column_names]
fbmh_df = old_fbmh_df[column_names]
#change index back to integer 
index = [i for i in range(53)]
ibhs_df.columns = index
fbmh_df.columns = index

In [6]:
xneed_real = twosum_improvement_xneed(ibhs_df, fbmh_df, groups_num = 100)

Using license file /Users/carayi/gurobi.lic
Academic license - for non-commercial use only


In [7]:
#initial - final
ibhs_df 

0   1   2   3   4   5   6   7   8   9   ...  43  44  45  46  47  48  49  \
0      0  -1   0   1   1   0   2   0   2   0  ...   0  -1   1   1   0  -1   0   
1      0   1   0   1   2   0   0   0   0   0  ...   1   1   2   1   1   1   2   
2     -2   0   0  -1   0  -1  -2   0   0   1  ...   0   2   0   0   0  -1   1   
3     -2   0   0   0   0  -1   0   0   0  -1  ...   0  -1   0   0   0   1   0   
4      0  -1  -1  -1   1  -1   1   0   0   0  ...   0   0   1   0   1   0  -1   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
3814   0   0   0   1   1   0   1   0   0   0  ...   0   1  -3   0   1   0   0   
3815   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0  -3   
3816   0   1   0   1   0   0   1   0   0   0  ...   0   0   0   1   0   0   0   
3817   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3818   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

      50  51  52  
0      0  -1   0  
1      1   0   0  
2     -1   0   0  
3     -1  -1  -1  
4      0   0   0  
...   ..  ..  ..  
3814   0   0   0  
3815   0  -2  -2  
3816   0   0   0  
3817   0   0   0  
3818   0   0   0  

[3819 rows x 53 columns]

In [8]:
xneed_real

array([ 0.38,  0.26, -0.42,  0.74,  0.44,  0.34,  0.34,  0.2 ,  0.78,
        0.78,  0.44,  0.08,  0.28, -0.06,  0.58,  0.04,  0.  ,  0.42,
        0.16,  0.14,  0.  , -0.14, -0.02,  0.6 ,  0.32,  0.04,  0.36,
       -0.14,  0.5 ,  0.38, -0.8 , -0.78, -0.74,  0.7 ,  0.58,  0.72,
        0.64,  0.76,  0.5 ,  0.48,  0.46,  0.5 ,  0.08,  0.56,  0.04,
        0.1 ,  0.16,  0.06, -0.4 , -0.04,  0.18,  0.16,  0.12])

In [9]:
# run the model for 60 times
n = 60
total = np.array([0.0 for i in range(53)])
for i in range(n):
    xneed_real = twosum_improvement_xneed(ibhs_df, fbmh_df, groups_num = 100)
    total += xneed_real

In [10]:
final_need = total/60

In [18]:
final_need

array([ 3.30000000e-01,  3.40666667e-01, -3.90666667e-01,  7.41333333e-01,
        3.81666667e-01,  3.13333333e-01,  3.82333333e-01,  2.55333333e-01,
        7.51666667e-01,  8.65666667e-01,  4.13000000e-01,  1.23333333e-02,
        3.81666667e-01, -1.38666667e-01,  4.77666667e-01,  1.31000000e-01,
        4.83333333e-02,  3.88333333e-01,  1.64333333e-01,  6.00000000e-03,
        2.50000000e-02, -1.03333333e-01, -3.33333333e-04,  5.85666667e-01,
        3.16666667e-01,  6.10000000e-02,  4.21666667e-01, -6.03333333e-02,
        5.15666667e-01,  4.54666667e-01, -7.12000000e-01, -6.91333333e-01,
       -7.03000000e-01,  7.16000000e-01,  4.62333333e-01,  6.55333333e-01,
        6.19666667e-01,  7.00666667e-01,  4.95000000e-01,  5.04666667e-01,
        3.73000000e-01,  5.86000000e-01,  3.66666667e-02,  5.49000000e-01,
        2.20000000e-02,  2.60000000e-02,  1.34666667e-01,  7.33333333e-02,
       -3.91666667e-01, -1.36666667e-02,  1.55333333e-01,  1.54000000e-01,
        1.12666667e-01])

#### Final Need Output <a name="final_need_output"></a>

In [22]:
#dictt = pd.read_csv('clean_fbmh_df.csv')
def map_to_real_need(need):
    return list(dictt.columns).index(need)

def map_to_need(number):
    return list(dictt.columns)[number + 1]

def write_to_final_needs(needs, filename):
    
    # writing to csv file 
    final_need_df = pd.DataFrame()
    final_need_df['needs'] = list(column_names_df['CDR CANS Label'])
    final_need_df['coef'] = final_need

    final_need_df.to_csv(filename, sep='\t')
    with open(filename, 'w') as csvfile: 
        # creating a csv writer object 
        csvwriter = csv.writer(csvfile) 
        
        # writing the fields 
        csvwriter.writerow(column_names) 

        # writing the data rows 
        csvwriter.writerows([list(needs)])

In [23]:
write_to_final_needs(final_need, 'final_need_coefficient.csv')

### Dummy Data <a name="dummy_data"></a>

#### Group 1 : <a name="dummy_group_1"></a>
5 correlated with IBHS, 5 correlated with FBMHS, 80 random, only
improvements, 30 patients

In [32]:
test_dummy_1_ibhs, test_dummy_1_fbmh = import_data('dummy_group_1_origin.csv')

In [33]:
xneed_1 = twosum_improvement_xneed(test_dummy_1_ibhs, test_dummy_1_fbmh, groups_num = 3)

In [34]:
xneed_1

array([-1.        , -1.        , -1.        , -1.        , -1.        ,
        0.33333333, -0.33333333,  0.33333333, -0.33333333,  0.33333333,
        0.33333333,  0.33333333,  1.        , -0.33333333,  0.33333333,
       -1.        , -0.33333333, -1.        , -1.        , -0.33333333,
       -0.33333333, -0.33333333,  0.33333333, -0.33333333,  1.        ,
       -0.33333333, -0.33333333, -1.        ,  1.        , -0.33333333,
       -1.        , -0.33333333, -0.33333333,  0.33333333,  0.33333333,
       -1.        , -0.33333333, -0.33333333, -1.        ,  0.33333333,
       -1.        ,  0.33333333, -0.33333333, -0.33333333,  0.33333333,
        0.33333333, -0.33333333, -0.33333333,  0.33333333, -0.33333333,
       -1.        , -1.        , -1.        , -0.33333333, -0.33333333,
        1.        ,  1.        ,  1.        ,  1.        , -0.33333333,
        0.33333333, -0.33333333, -0.33333333, -0.33333333, -0.33333333,
       -1.        ,  0.33333333, -0.33333333,  1.        , -0.33